cybercongress/cyber-search

address-summary/bitcoin/src/main/kotlin/fund/cyber/address/bitcoin/summary/BitcoinAddressSummaryDelta.kt
address-summary/build.gradle
address-summary/common/src/main/kotlin/fund/cyber/address/common/CommonConfiguration.kt
address-summary/common/src/main/kotlin/fund/cyber/address/common/delta/apply/UpdateAddressSummaryProcess.kt
address-summary/common/src/main/resources/application.yml
address-summary/ethereum/src/main/kotlin/fund/cyber/address/ethereum/delta/apply/EthereumConsumerConfiguration.kt
devops/metrics/Ethereum Address Summary.json
devops/metrics/Ethereum Dump.json
dumps/build.gradle
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/ApplcationConfiguration.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/BlockDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/TxDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/UncleDumpProcess.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/monitoring/LastNetworkBlockNumberMonitoring.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/PumpApplication.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/monitoring/LastTopicOffsetMonitoring.kt

Monitoring for dump and address summary

54 address monitoring

---

.circleci/config.yml
address-summary/common/src/main/kotlin/fund/cyber/address/common/delta/apply/UpdateAddressSummaryProcess.kt
address-summary/ethereum/Dockerfile
address-summary/ethereum/src/main/kotlin/fund/cyber/address/ethereum/summary/EthereumAddressSummaryDelta.kt

Address summary docker container

#54 Apply delta to address. Docker container.

---

address-summary/bitcoin/src/main/kotlin/fund/cyber/address/bitcoin/BitcoinAddressSummaryStorage.kt
address-summary/bitcoin/src/main/kotlin/fund/cyber/address/bitcoin/delta/apply/BitcoinTxConsumerConfiguration.kt
address-summary/common/src/main/kotlin/fund/cyber/address/common/delta/apply/AddressLockException.kt
address-summary/common/src/main/kotlin/fund/cyber/address/common/delta/apply/UpdateAddressSummaryProcess.kt
address-summary/common/src/main/kotlin/fund/cyber/address/common/summary/AddressSummaryStorage.kt
address-summary/ethereum/src/main/kotlin/fund/cyber/address/ethereum/EthereumAddressSummaryStorage.kt
address-summary/ethereum/src/main/kotlin/fund/cyber/address/ethereum/delta/apply/EthereumConsumerConfiguration.kt
common-kafka/src/main/kotlin/fund/cyber/common/kafka/reader/SinglePartitionTopicLastItemsReader.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt

Apply addresses. Handle locks.

#54 Apply addresses. Handle locks.

---

address-summary/common/src/main/kotlin/fund/cyber/address/common/delta/apply/UpdateAddressSummaryProcess.kt
address-summary/ethereum/src/main/kotlin/fund/cyber/address/ethereum/summary/EthereumAddressSummaryDelta.kt
address-summary/ethereum/src/test/kotlin/fund/cyber/address/ethereum/EthereumTxDeltaProcessorTest.kt

Fix Ethereum transaction delta calculation.

Fix Ethereum transaction delta calculation.

---

common-kafka/src/test/kotlin/fund/cyber/common/kafka/SinglePartitionTopicDataPresentLatch.kt
common-kafka/src/test/kotlin/fund/cyber/common/kafka/reader/SinglePartitionLackOfRecordsReaderTest.kt
common-kafka/src/test/kotlin/fund/cyber/common/kafka/reader/SinglePartitionMultipleTransactionRecordReaderTest.kt
common-kafka/src/test/kotlin/fund/cyber/common/kafka/reader/SinglePartitionSingeTransactionRecordReaderTest.kt

Fix single partition topic last item reader tests.

Fix single partition topic last item reader tests.

---

pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/BitcoinBlockchainInterface.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/BitcoinClientConfiguration.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/kafka/BitcoinBundleProducerConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/node/FlowableBlockchainInterface.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/client/EthereumBlockchainInterface.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/client/EthereumClientConfiguration.kt

#65 Pump stuck after exception

#65 Pump stuck after exception.

---

pumps/common/src/main/kotlin/fund/cyber/pump/common/ChainPump.kt

Zoombied Ethereum Pump Instance

#77 Zoombied Ethereum Pump Instance

---

address-summary/ethereum/src/test/kotlin/fund/cyber/address/ethereum/EthereumBlockDeltaProcessorTest.kt
address-summary/ethereum/src/test/kotlin/fund/cyber/address/ethereum/EthereumTxDeltaProcessorTest.kt
address-summary/ethereum/src/test/kotlin/fund/cyber/address/ethereum/EthereumUncleDeltaProcessorTest.kt
build.gradle
common/src/main/kotlin/fund/cyber/common/StackCache.kt
common/src/main/kotlin/fund/cyber/search/configuration/Env.kt
common/src/test/kotlin/fund/cyber/node/common/StackCacheTest.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/BlockDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/Functions.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/TxDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/UncleDumpProcess.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/BlockDumpProcessTest.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/TxDumpProcessTest.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/UncleDumpProcessTest.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/kafka/BitcoinBundleProducer.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/ChainPump.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/kafka/KafkaBlockBundleProducer.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/node/BlockBundleEventGenerator.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/node/BlockBundleMapper.kt
pumps/common/src/test/kotlin/fund/cyber/pump/common/node/BlockBundleEventGeneratorTest.kt
pumps/common/src/test/kotlin/fund/cyber/pump/common/node/BlockBundleMapperTest.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/kafka/EthereumBlockBundleProducer.kt

#72 Realtime chain reorganisation

---

pumps/common/src/main/kotlin/fund/cyber/pump/common/node/BlockBundleEventGenerator.kt

Realtime chain reorganisation. Logs.

Realtime chain reorganisation. Logs.

---

cassandra-service/src/main/resources/migrations/ethereum_classic/0_initial.cql

Fix ethereum classic migration script

Fix ethereum classic migration script

---

common/src/main/kotlin/fund/cyber/search/configuration/Env.kt
common/src/main/resources/logback.xml
dev-environment/env.yml
pumps/common/src/main/kotlin/fund/cyber/pump/common/node/BlockBundleEventGenerator.kt
pumps/common/src/test/kotlin/fund/cyber/pump/common/node/BlockBundleEventGeneratorTest.kt

Pump stuck if chain reorganization bundles number exceed history stack size

#99 Pump stuck if chain reorganization bundles number exceed history stack size

---

search-api/src/main/kotlin/fund/cyber/api/common/Func.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/AddressHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/TxHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/functions/AddressTxesByAddress.kt
search-api/src/test/kotlin/fund/cyber/api/common/FuncTest.kt

Make chain items retrivial caps non-depended

#98 Make chain items retrivial caps non-depended

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/configuration/BitcoinRepositoryConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/model/Address.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/model/Block.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/repository/AddressSummaryRepositories.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/repository/TxRepositories.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/configuration/EthereumRepositoryConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/repository/AddressRepositories.kt
docs/Dockerfile
docs/bitcoin.v1.yaml
docs/ethereum.v1.yaml
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/TxDumpProcess.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/AddressHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/BlockHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/TxHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/functions/AddressBlocksByAddress.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/functions/AddressTxesByAddress.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/functions/BlockTxesByBlockNumber.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/AddressHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/UncleHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/functions/AddressBlocksByAddress.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/functions/AddressUnclesByAddress.kt

#84 API: bitcoin endpoints

---

.circleci/config.yml

Fix Circle CI for bitcoin

---

cassandra-service/src/main/resources/migrations/bitcoin/5_create-address-index.json
cassandra-service/src/main/resources/migrations/bitcoin/6_create-address-type.json
cassandra-service/src/main/resources/migrations/bitcoin_cash/1_create-tx-index.json
cassandra-service/src/main/resources/migrations/bitcoin_cash/2_create-tx-type.json
cassandra-service/src/main/resources/migrations/bitcoin_cash/3_create-block-index.json
cassandra-service/src/main/resources/migrations/bitcoin_cash/4_create-block-type.json
cassandra-service/src/main/resources/migrations/bitcoin_cash/5_create-address-index.json
cassandra-service/src/main/resources/migrations/bitcoin_cash/6_create-address-type.json
docs/bitcoin.v1.yaml
docs/ethereum.v1.yaml
docs/search.v1.yaml
search-api/src/main/kotlin/fund/cyber/api/search/SearchController.kt

Add filter params for search api

#106 Add filter params for search api

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/configuration/BitcoinRepositoryConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/model/Contract.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/configuration/CassandraConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/configuration/EthereumRepositoryConfiguration.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/BlockHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/ContractHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/TxHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/common/CommonConfiguration.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/AddressHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/BlockHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/TxHandlers.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/UncleHandlers.kt

Make search API logic dependent of existing keyspaces

#113 Make search API logic dependent of existing keyspaces

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/configuration/BitcoinRepositoryConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/repository/UpdateContractSummaryRepository.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/configuration/CassandraConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/configuration/EthereumRepositoryConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/repository/UpdateContractSummaryRepository.kt
common-kafka/src/main/kotlin/fund/cyber/common/kafka/Configuration.kt
contract-summary/bitcoin/src/main/kotlin/fund/cyber/contract/bitcoin/BitcoinContractSummaryStorage.kt
contract-summary/bitcoin/src/main/kotlin/fund/cyber/contract/bitcoin/delta/apply/BitcoinTxConsumerConfiguration.kt
contract-summary/ethereum/src/main/kotlin/fund/cyber/contract/ethereum/EthereumContractSummaryStorage.kt
contract-summary/ethereum/src/main/kotlin/fund/cyber/contract/ethereum/delta/apply/EthereumConsumerConfiguration.kt

Contract summary. Fix findAllByHash function

Contract summary. Fix findAllByHash function

---

README.md
ROADMAP.md

@arturalbov @asadovka Please, leave comments.

#20 Open Source Features

---

CHANGELOG.md

Update changelog with 0.4.0 version

Update changelog with 0.4.0 version

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/model/Contract.kt
cassandra-service/src/main/resources/migrations/ethereum/0_initial.cql
cassandra-service/src/main/resources/migrations/ethereum_classic/0_initial.cql
contract-summary/common/src/main/kotlin/fund/cyber/contract/common/delta/apply/UpdateContractSummaryProcess.kt
contract-summary/ethereum/src/main/kotlin/fund/cyber/contract/ethereum/summary/EthereumContractSummaryDelta.kt
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/BlockDumpProcess.kt
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/TxDumpProcess.kt
dumps/common/src/test/kotlin/fund/cyber/dump/common/FuntionsTest.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/BlockDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/TxDumpProcess.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/TxDumpProcessTest.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/BitcoinClientConfiguration.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/client/ParityToEthereumBundleConverter.kt

Refactoring of cassandra dump logic

Refactoring of cassandra dump logic

---

pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/BitcoinClientConfiguration.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/monitoring/CacheMonitoring.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt

Bitcoin Transactions Outputs Cache Monitoring. Prometheus metrics

Bitcoin Transactions Outputs Cache Monitoring. Prometheus metrics

---

common/src/main/kotlin/fund/cyber/search/configuration/Env.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/BitcoinClientConfiguration.kt

Make bitcoin tx outputs cache heap size environment variable

Make bitcoin tx outputs cache heap size environment variable

---

dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/ApplicationConfiguration.kt
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/BlockDumpProcess.kt
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/TxDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/ApplcationConfiguration.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/BlockDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/TxDumpProcess.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/UncleDumpProcess.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/BlockDumpProcessTest.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/TxDumpProcessTest.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/UncleDumpProcessTest.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/kafka/KafkaProducerConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/pool/KafkaPoolItemProducer.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/pool/PoolPump.kt

Setup ethereum mempool monitoring

Setup ethereum mempool monitoring

---

CHANGELOG.md

Update changelog with 0.5.0 release

Update changelog with 0.5.0 release

---

supply/common/src/main/kotlin/fund/cyber/supply/CommonConfiguration.kt
supply/common/src/main/kotlin/fund/cyber/supply/common/CurrentSupplyProvider.kt
supply/ethereum/src/main/kotlin/fund/cyber/supply/SupplyApplication.kt
supply/ethereum/src/main/kotlin/fund/cyber/supply/ethereum/ApplicationConfiguration.kt
supply/ethereum/src/test/kotlin/fund/cyber/supply/ethereum/EthereumSupplyBaseTest.kt

#166 ETH Supply Service

---

.circleci/config.yml
contract-summary/bitcoin/Dockerfile
contract-summary/ethereum/Dockerfile
dumps/bitcoin/Dockerfile
dumps/ethereum/Dockerfile
pumps/bitcoin/Dockerfile
pumps/ethereum/Dockerfile
search-api/Dockerfile
supply/ethereum/Dockerfile

Make Circle Ci docker builds cacheable #184
What done:
- created workspace that shares files between jobs
- build of project now happens only ones
- decrease size of docker context

Make Circle Ci docker builds cacheable

---

build.gradle
cassandra-service/src/test/kotlin/fund/cyber/cassandra/AllChainContextStartUp.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/BitcoinContextStartUpTest.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/RoutingReactiveCassandraRepositoryTest.kt
cassandra-service/src/test/resources/create-chains-keyspaces.cql
gradle/coverage-subprojects.gradle
gradle/coverage.gradle
gradle/repositories.gradle

--cassandra module context tests

 Add Context Loading Unit Tests #199

---

common/src/main/kotlin/fund/cyber/common/StringUtils.kt
contract-summary/common/src/main/kotlin/fund/cyber/contract/common/CommonConfiguration.kt
contract-summary/ethereum/src/main/kotlin/fund/cyber/UpdateEthereumContractSummaryApplication.kt
contract-summary/ethereum/src/main/kotlin/fund/cyber/contract/ethereum/EthereumConsumerConfiguration.kt
docs/api/search.v1.yaml
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/client/TxExecutionTraceConverter.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/trace/TxTraceConstructedForErroredTxTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/trace/TxTraceConstructedForMethodCallInvokingContractCreationTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/trace/TxTraceConstructedForMethodCallInvokingContractDestroyTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/trace/TxTraceConstructedForNormalTxTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/trace/TxTraceConstructedForRevertedTxTest.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/dto/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Block.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Transaction.kt
search-api/src/main/kotlin/fund/cyber/api/common/CommonConfiguration.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/dto/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Block.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Transaction.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Uncle.kt
search-api/src/main/kotlin/fund/cyber/api/search/ElasticResponse.kt
search-api/src/main/kotlin/fund/cyber/api/search/SearchController.kt
search-api/src/main/resources/application.yml

Refactoring of search API

---

cassandra-service/src/test/kotlin/fund/cyber/cassandra/EthereumContextStartUpTest.kt
contract-summary/bitcoin/Dockerfile
contract-summary/ethereum/Dockerfile
docs/contributing/pump-development.md
dumps/bitcoin/Dockerfile
dumps/ethereum/Dockerfile
pumps/bitcoin/Dockerfile
pumps/ethereum/Dockerfile
search-api/Dockerfile
supply/ethereum/Dockerfile

Our tests running only java 8, also, some features compiled on java 8,
do not working on java 10. So, try to use java 8 everywhere.

Use Java 8 instead of 10

---

common-kafka/src/main/kotlin/fund/cyber/common/kafka/Func.kt
common/src/main/kotlin/fund/cyber/search/model/chains/ChainInfo.kt
common/src/main/kotlin/fund/cyber/search/model/ethereum/Block.kt
common/src/main/kotlin/fund/cyber/search/model/ethereum/Uncle.kt
common/src/main/kotlin/fund/cyber/search/model/events/Topics.kt
docs/contributing/pump-development.md
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/BitcoinBlockchainInterface.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/ChainPump.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/kafka/KafkaProducerConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/pool/PoolPump.kt
supply/common/src/main/kotlin/fund/cyber/supply/CommonConfiguration.kt

Pump: Retry kafka store operation after exception

Pump: Retry kafka store operation after exception

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/model/Contract.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/model/Transaction.kt
cassandra-service/src/main/resources/migrations/bitcoin/0_initial.cql
contract-summary/bitcoin/src/main/kotlin/fund/cyber/contract/bitcoin/delta/apply/BitcoinTxConsumerConfiguration.kt
contract-summary/common/src/main/kotlin/fund/cyber/contract/common/delta/apply/UpdateContractSummaryProcess.kt
search-api/src/main/kotlin/fund/cyber/SearchApiApplication.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/dto/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Block.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/common/CommonConfiguration.kt
search-api/src/main/kotlin/fund/cyber/api/common/Request.kt
search-api/src/main/kotlin/fund/cyber/api/common/RequestHandler.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Block.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Contract.kt

Update bitcoin contract summary search API

Update bitcoin contract summary search API

---

common/src/main/kotlin/fund/cyber/common/Time.kt
common/src/main/resources/logback.xml
contract-summary/bitcoin/src/main/kotlin/fund/cyber/contract/bitcoin/delta/apply/BitcoinTxConsumerConfiguration.kt
contract-summary/common/src/main/kotlin/fund/cyber/contract/common/CommonConfiguration.kt
contract-summary/ethereum/src/main/kotlin/fund/cyber/contract/ethereum/EthereumConsumerConfiguration.kt
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/BitcoinMessageListenerResolver.kt
dumps/bitcoin/src/main/kotlin/fund/cyber/dump/bitcoin/TxDumpProcess.kt
dumps/bitcoin/src/test/kotlin/fund/cyber/dump/bitcoin/TxDumpProcessTest.kt
dumps/common/src/main/kotlin/fund/cyber/dump/common/CommonConfiguration.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/EthereumMessageListenerResolver.kt
dumps/ethereum/src/main/kotlin/fund/cyber/dump/ethereum/TxDumpProcess.kt
dumps/ethereum/src/test/kotlin/fund/cyber/dump/ethereum/TxDumpProcessTest.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt

- add chain family prometheus tag
- add tx latency metrics

cybercongress/cybernode#90 Make chains monitoring templateable.

---

common-kafka/src/main/kotlin/fund/cyber/common/kafka/Configuration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/kafka/KafkaProducerConfiguration.kt
pumps/common/src/main/kotlin/fund/cyber/pump/common/kafka/LastPumpedBundlesProvider.kt

Replicate kafka consumer group commited offsets

Replicate kafka consumer group commited offsets

---

build.gradle
cassandra-service/src/test/kotlin/fund/cyber/cassandra/AllChainContextStartUp.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/BitcoinContextStartUpTest.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/CassandraTestBase.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/CassandraTestExecutionListener.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/EthereumContextStartUpTest.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/RoutingReactiveCassandraRepositoryTest.kt
common-kafka/src/test/kotlin/fund/cyber/common/kafka/BaseForKafkaIntegrationTest.kt
contract-summary/bitcoin/src/main/kotlin/fund/cyber/contract/bitcoin/BitcoinTxConsumerConfiguration.kt
contract-summary/bitcoin/src/main/kotlin/fund/cyber/contract/bitcoin/delta/BitcoinContractSummaryDelta.kt
contract-summary/bitcoin/src/test/kotlin/fund/cyber/contract/bitcoin/delta/BitcoinContractSummaryDeltaTest.kt
contract-summary/bitcoin/src/test/kotlin/fund/cyber/contract/bitcoin/delta/BitcoinDeltaTestData.kt
contract-summary/bitcoin/src/test/kotlin/fund/cyber/contract/bitcoin/delta/BitcoinTxDeltaProcessorTest.kt
contract-summary/bitcoin/src/test/kotlin/fund/cyber/contract/bitcoin/delta/ContextStartUpTest.kt
contract-summary/build.gradle
contract-summary/common/src/test/kotlin/fund/cyber/contract/delta/apply/UpdateContractSummaryProcessTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/ContextStartUpTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/EthereumBlockDeltaProcessorTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/EthereumUncleDeltaProcessorTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/delta/EthereumContractSummaryDeltaTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/delta/EthereumDeltaMergerTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/delta/EthereumTxDeltaProcessorTest.kt
contract-summary/ethereum/src/test/kotlin/fund/cyber/contract/ethereum/delta/EthereumTxDeltaProcessorTestData.kt

Contract Summary Module Tests

---

.circleci/config.yml
build.gradle
cassandra-service/src/test/kotlin/fund/cyber/cassandra/CassandraTestBase.kt
cassandra-service/src/test/kotlin/fund/cyber/cassandra/CassandraTestExecutionListener.kt
search-api/src/test/kotlin/fund/cyber/api/ApiTest.kt
search-api/src/test/resources/cassandra-bitcoin-data.cql
search-api/src/test/resources/cassandra-ethereum-data.cql

Search API Module Tests

---

common/src/main/kotlin/fund/cyber/search/model/bitcoin/BitcoinJsonRpc.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/converter/JsonRpcBlockToBitcoinBundleConverter.kt
pumps/bitcoin/src/main/kotlin/fund/cyber/pump/bitcoin/client/converter/JsonRpcToDaoBitcoinBlockConverter.kt
pumps/bitcoin/src/test/kotlin/fund/cyber/pump/bitcoin/client/BitcoinBlockchainInterfaceTest.kt
pumps/bitcoin/src/test/kotlin/fund/cyber/pump/bitcoin/client/BitcoinTxOutputsStorageTest.kt
pumps/bitcoin/src/test/kotlin/fund/cyber/pump/bitcoin/client/BtcdToBundleConverterTest.kt
pumps/bitcoin/src/test/kotlin/fund/cyber/pump/bitcoin/client/BtcdToDaoBlockConverterTest.kt
pumps/bitcoin/src/test/kotlin/fund/cyber/pump/bitcoin/client/BtcdToDaoTransactionConverterTest.kt
pumps/bitcoin/src/test/kotlin/fund/cyber/pump/bitcoin/client/ContextStartUpTest.kt
pumps/build.gradle
pumps/common/src/main/kotlin/fund/cyber/pump/common/CommonConfiguration.kt
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/client/ParityToEthereumBundleConverter.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/ContextStartUpTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/EthereumBlockchainInterfaceTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/ParityTestData.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/ParityToEthereumBundleConverterTest.kt
pumps/ethereum/src/test/resources/client/parity-data/block/1.json
pumps/ethereum/src/test/resources/client/parity-data/receipts/0xd7b10b163b1de8f8967d824ea73d996c476588a91a4c714ad897b135cf7fa4c5.json
pumps/ethereum/src/test/resources/client/parity-data/traces/1.json
pumps/ethereum/src/test/resources/client/parity-data/transaction/0xc713064951e38f55b167c483a882bd1550b12d58c552800e1e25a764e70a6894.json
pumps/ethereum/src/test/resources/client/parity-data/uncles/0xB_0.json
search-api/src/test/kotlin/fund/cyber/api/ApiTest.kt
supply/ethereum/src/test/kotlin/fund/cyber/supply/ethereum/EthereumSupplyBaseTest.kt

Pump Modules Tests

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/configuration/BitcoinRepositoriesConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/common/RepositoriesConfiguration.kt
cassandra-service/src/main/kotlin/fund/cyber/cassandra/ethereum/configuration/EthereumRepositoriesConfiguration.kt
docs/components/cassandra-service.md
search-api/src/main/kotlin/fund/cyber/api/common/CommonConfiguration.kt
search-api/src/main/kotlin/fund/cyber/api/common/RequestHandler.kt

Describe cassandra-service context start-up.
Plus some minor refactoring of cassandra-service

Describe cassandra-service context start-up

---

common/src/main/kotlin/fund/cyber/common/StringUtils.kt
docs/contributing/cheat-sheet.md
docs/contributing/dev-environment.md
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Transaction.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Uncle.kt
search-api/src/main/kotlin/fund/cyber/api/search/SearchController.kt

Fix Search API. Make ethereum hashes case insensitive. Remove hash prefix on search.

 Fix Search API. Make ethereum hashes case insensitive. Remove hash prefix on search.

---

cassandra-service/src/main/kotlin/fund/cyber/cassandra/bitcoin/model/Transaction.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Block.kt
search-api/src/main/kotlin/fund/cyber/api/bitcoin/handlers/Contract.kt
search-api/src/main/kotlin/fund/cyber/api/common/CommonConfiguration.kt
search-api/src/main/kotlin/fund/cyber/api/common/Request.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Block.kt
search-api/src/main/kotlin/fund/cyber/api/ethereum/handlers/Contract.kt
search-api/src/test/kotlin/fund/cyber/api/ApiTest.kt
search-api/src/test/kotlin/fund/cyber/api/ApiTestData.kt
search-api/src/test/resources/cassandra-bitcoin-data.cql

also #248 Set pageable endpoints pageSize limits

#249 Wrong order of transactions in

---

common/src/main/kotlin/fund/cyber/search/model/bitcoin/Block.kt
common/src/test/kotlin/fund/cyber/search/model/bitcoin/BlockTest.kt

- Use formula to calculate bitcoin block reward given block number

Improve BitcoinBlock getBlockReward

---

common/src/main/kotlin/fund/cyber/search/model/ethereum/Block.kt
common/src/main/kotlin/fund/cyber/search/model/ethereum/Uncle.kt
gradle/coverage-subprojects.gradle
gradle/coverage.gradle
pumps/ethereum/src/main/kotlin/fund/cyber/pump/ethereum/client/ParityToEthereumBundleConverter.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/EthereumBlockchainInterfaceTest.kt
pumps/ethereum/src/test/kotlin/fund/cyber/pump/ethereum/client/ParityToEthereumBundleConverterTest.kt
pumps/ethereum/src/test/resources/client/parity-data/block/6149845.json
pumps/ethereum/src/test/resources/client/parity-data/block/6154914.json
pumps/ethereum/src/test/resources/client/parity-data/traces/1.json
pumps/ethereum/src/test/resources/client/parity-data/traces/6149845.json
pumps/ethereum/src/test/resources/client/parity-data/traces/6154914.json
pumps/ethereum/src/test/resources/client/parity-data/uncles/0x02e2ee54556a80710af3f80691781bf4eae37ae869d40bcf46b4186aeb6ce4d7_0.json
pumps/ethereum/src/test/resources/client/parity-data/uncles/0x02e2ee54556a80710af3f80691781bf4eae37ae869d40bcf46b4186aeb6ce4d7_1.json
pumps/ethereum/src/test/resources/client/parity-data/uncles/0x12e2ee54556a80710af3f80691781bf4eae37ae869d40bcf46b4186aeb6ce4d7_0.json
pumps/ethereum/src/test/resources/client/parity-data/uncles/0x12e2ee54556a80710af3f80691781bf4eae37ae869d40bcf46b4186aeb6ce4d7_1.json

#185 ETH: calculate block & uncle rewards from block traces

---

.circleci/config.yml

Change knowledge folder to wiki according to new structure

Redirect commits to wiki folder
